[package]
name = "vulkan_test"
version = "0.1.0"
authors = ["Jeroen Rietveld <jf.rietveld@gmail.com>"]

[dependencies]
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
vulkano-win = "0.9.0"
vulkano_text = "0.7"
winit = "0.11.0"
cgmath = "0.16.1"
time = "0.1.40"